-- ============================================================================
-- DYNAMIC TABLES FOR INVENTORY ANALYSIS
-- File: 03_dynamic_tables_actual.sql
-- Description: Creates dynamic tables for real-time inventory analysis
-- Created: 2026-01-04
-- ============================================================================

-- ============================================================================
-- 1. LOW STOCK ALERT DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_LOW_STOCK_ALERTS
TARGET LAG = 1 HOUR
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    ABC_CLASS,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SAFETY_STOCK,
    DAYS_OF_INVENTORY,
    (REORDER_POINT - QUANTITY_ON_HAND) AS UNITS_BELOW_REORDER,
    LEAD_TIME_DAYS,
    AVG_DAILY_SALES,
    FORECAST_NEXT_30D,
    INVENTORY_STATUS,
    DEMAND_FORECAST_ACCURACY_PCT,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE QUANTITY_ON_HAND < REORDER_POINT
    AND INVENTORY_STATUS != 'DISCONTINUED'
ORDER BY UNITS_BELOW_REORDER DESC;

-- ============================================================================
-- 2. HIGH VALUE INVENTORY DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_HIGH_VALUE_INVENTORY
TARGET LAG = 2 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    ABC_CLASS,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    QUANTITY_ON_HAND,
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE_USD,
    QUANTITY_RESERVED,
    QUANTITY_COMMITTED,
    EXPIRY_DATE,
    INVENTORY_STATUS,
    AUDIT_VARIANCE_PCT,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE TOTAL_INVENTORY_VALUE_USD > (
    SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY TOTAL_INVENTORY_VALUE_USD)
    FROM CLEANED_INVENTORY
)
ORDER BY TOTAL_INVENTORY_VALUE_USD DESC;

-- ============================================================================
-- 3. INVENTORY VARIANCE ANALYSIS DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_INVENTORY_VARIANCE
TARGET LAG = 6 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    ABC_CLASS,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    QUANTITY_ON_HAND,
    AUDIT_VARIANCE_PCT,
    UNIT_COST_USD,
    (AUDIT_VARIANCE_PCT / 100.0 * QUANTITY_ON_HAND * UNIT_COST_USD) AS VARIANCE_VALUE_USD,
    CASE 
        WHEN AUDIT_VARIANCE_PCT > 5 THEN 'HIGH'
        WHEN AUDIT_VARIANCE_PCT > 2 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS VARIANCE_SEVERITY,
    INVENTORY_STATUS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE ABS(AUDIT_VARIANCE_PCT) > 0
ORDER BY ABS(AUDIT_VARIANCE_PCT) DESC;

-- ============================================================================
-- 4. DEMAND FORECAST VS ACTUAL DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_FORECAST_ANALYSIS
TARGET LAG = 1 HOUR
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    ABC_CLASS,
    AVG_DAILY_SALES,
    FORECAST_NEXT_30D,
    DAYS_OF_INVENTORY,
    DEMAND_FORECAST_ACCURACY_PCT,
    CASE
        WHEN DEMAND_FORECAST_ACCURACY_PCT >= 90 THEN 'EXCELLENT'
        WHEN DEMAND_FORECAST_ACCURACY_PCT >= 75 THEN 'GOOD'
        WHEN DEMAND_FORECAST_ACCURACY_PCT >= 60 THEN 'FAIR'
        ELSE 'POOR'
    END AS FORECAST_QUALITY,
    (FORECAST_NEXT_30D - (AVG_DAILY_SALES * 30)) AS FORECAST_VARIANCE,
    QUANTITY_ON_HAND,
    SAFETY_STOCK,
    LEAD_TIME_DAYS,
    INVENTORY_STATUS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE ABC_CLASS IS NOT NULL
ORDER BY DEMAND_FORECAST_ACCURACY_PCT ASC;

-- ============================================================================
-- 5. WAREHOUSE INVENTORY SUMMARY DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_WAREHOUSE_SUMMARY
TARGET LAG = 2 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    COUNT(DISTINCT SKU_ID) AS TOTAL_SKUS,
    COUNT(DISTINCT CATEGORY) AS UNIQUE_CATEGORIES,
    SUM(QUANTITY_ON_HAND) AS TOTAL_QUANTITY_ON_HAND,
    SUM(QUANTITY_RESERVED) AS TOTAL_QUANTITY_RESERVED,
    SUM(QUANTITY_COMMITTED) AS TOTAL_QUANTITY_COMMITTED,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS WAREHOUSE_TOTAL_VALUE_USD,
    AVG(DAYS_OF_INVENTORY) AS AVG_DAYS_OF_INVENTORY,
    AVG(AUDIT_VARIANCE_PCT) AS AVG_AUDIT_VARIANCE_PCT,
    COUNT(CASE WHEN INVENTORY_STATUS = 'OVERSTOCK' THEN 1 END) AS OVERSTOCK_ITEMS,
    COUNT(CASE WHEN INVENTORY_STATUS = 'UNDERSTOCK' THEN 1 END) AS UNDERSTOCK_ITEMS,
    COUNT(CASE WHEN INVENTORY_STATUS = 'OUT_OF_STOCK' THEN 1 END) AS OUT_OF_STOCK_ITEMS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
GROUP BY WAREHOUSE_ID, WAREHOUSE_LOCATION
ORDER BY WAREHOUSE_TOTAL_VALUE_USD DESC;

-- ============================================================================
-- 6. ABC CLASS PERFORMANCE DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_ABC_PERFORMANCE
TARGET LAG = 3 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    ABC_CLASS,
    COUNT(DISTINCT SKU_ID) AS ITEM_COUNT,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS CLASS_TOTAL_VALUE_USD,
    AVG(TOTAL_INVENTORY_VALUE_USD) AS AVG_ITEM_VALUE_USD,
    SUM(QUANTITY_ON_HAND) AS TOTAL_QUANTITY,
    AVG(DAYS_OF_INVENTORY) AS AVG_DAYS_OF_INVENTORY,
    AVG(DEMAND_FORECAST_ACCURACY_PCT) AS AVG_FORECAST_ACCURACY_PCT,
    AVG(SUPPLIER_ONTIME_PCT) AS AVG_SUPPLIER_ONTIME_PCT,
    COUNT(CASE WHEN INVENTORY_STATUS = 'OVERSTOCK' THEN 1 END) AS OVERSTOCK_COUNT,
    COUNT(CASE WHEN INVENTORY_STATUS = 'UNDERSTOCK' THEN 1 END) AS UNDERSTOCK_COUNT,
    COUNT(CASE WHEN INVENTORY_STATUS = 'OUT_OF_STOCK' THEN 1 END) AS OUT_OF_STOCK_COUNT,
    ROUND(100.0 * COUNT(CASE WHEN INVENTORY_STATUS = 'NORMAL' THEN 1 END) / COUNT(*), 2) AS PCT_NORMAL_STATUS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE ABC_CLASS IS NOT NULL
GROUP BY ABC_CLASS
ORDER BY CLASS_TOTAL_VALUE_USD DESC;

-- ============================================================================
-- 7. EXPIRING INVENTORY DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_EXPIRING_INVENTORY
TARGET LAG = 1 HOUR
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    QUANTITY_ON_HAND,
    EXPIRY_DATE,
    DATEDIFF(DAY, CURRENT_DATE(), EXPIRY_DATE) AS DAYS_TO_EXPIRY,
    UNIT_COST_USD,
    (QUANTITY_ON_HAND * UNIT_COST_USD) AS INVENTORY_VALUE_AT_RISK_USD,
    CASE
        WHEN DATEDIFF(DAY, CURRENT_DATE(), EXPIRY_DATE) <= 30 THEN 'CRITICAL'
        WHEN DATEDIFF(DAY, CURRENT_DATE(), EXPIRY_DATE) <= 90 THEN 'WARNING'
        ELSE 'MONITOR'
    END AS EXPIRY_URGENCY,
    INVENTORY_STATUS,
    AVG_DAILY_SALES,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE EXPIRY_DATE IS NOT NULL
    AND DATEDIFF(DAY, CURRENT_DATE(), EXPIRY_DATE) > 0
ORDER BY DAYS_TO_EXPIRY ASC;

-- ============================================================================
-- 8. SUPPLY CHAIN EFFICIENCY DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_SUPPLY_CHAIN_EFFICIENCY
TARGET LAG = 4 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    ABC_CLASS,
    LEAD_TIME_DAYS,
    SUPPLIER_ONTIME_PCT,
    DEMAND_FORECAST_ACCURACY_PCT,
    AVG_DAILY_SALES,
    SAFETY_STOCK,
    REORDER_POINT,
    QUANTITY_ON_HAND,
    DAYS_OF_INVENTORY,
    CASE
        WHEN SUPPLIER_ONTIME_PCT >= 95 AND DEMAND_FORECAST_ACCURACY_PCT >= 85 THEN 'EFFICIENT'
        WHEN SUPPLIER_ONTIME_PCT >= 85 AND DEMAND_FORECAST_ACCURACY_PCT >= 70 THEN 'ACCEPTABLE'
        ELSE 'NEEDS_IMPROVEMENT'
    END AS EFFICIENCY_STATUS,
    (LEAD_TIME_DAYS * AVG_DAILY_SALES) AS LEAD_TIME_DEMAND,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
ORDER BY SUPPLIER_ONTIME_PCT DESC, DEMAND_FORECAST_ACCURACY_PCT DESC;

-- ============================================================================
-- 9. QUANTITY DISCREPANCY DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_QUANTITY_DISCREPANCY
TARGET LAG = 1 HOUR
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_ID,
    WAREHOUSE_LOCATION,
    QUANTITY_ON_HAND,
    QUANTITY_RESERVED,
    QUANTITY_COMMITTED,
    (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) AS AVAILABLE_QUANTITY,
    CASE
        WHEN (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) < 0 THEN 'OVERSOLD'
        WHEN QUANTITY_RESERVED > (QUANTITY_ON_HAND * 0.8) THEN 'HEAVILY_RESERVED'
        WHEN QUANTITY_COMMITTED > (QUANTITY_ON_HAND * 0.8) THEN 'HEAVILY_COMMITTED'
        ELSE 'BALANCED'
    END AS ALLOCATION_STATUS,
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE_USD,
    INVENTORY_STATUS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
ORDER BY AVAILABLE_QUANTITY ASC;

-- ============================================================================
-- 10. CATEGORY PERFORMANCE DYNAMIC TABLE
-- ============================================================================
CREATE OR REPLACE DYNAMIC TABLE DT_CATEGORY_PERFORMANCE
TARGET LAG = 3 HOURS
WAREHOUSE = COMPUTE_WH
AS
SELECT
    CATEGORY,
    COUNT(DISTINCT SKU_ID) AS ITEM_COUNT,
    SUM(QUANTITY_ON_HAND) AS TOTAL_QUANTITY,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS CATEGORY_TOTAL_VALUE_USD,
    AVG(UNIT_COST_USD) AS AVG_UNIT_COST_USD,
    SUM(AVG_DAILY_SALES) AS TOTAL_DAILY_SALES,
    AVG(DAYS_OF_INVENTORY) AS AVG_DAYS_OF_INVENTORY,
    AVG(DEMAND_FORECAST_ACCURACY_PCT) AS AVG_FORECAST_ACCURACY_PCT,
    AVG(SUPPLIER_ONTIME_PCT) AS AVG_SUPPLIER_ONTIME_PCT,
    COUNT(CASE WHEN ABC_CLASS = 'A' THEN 1 END) AS CLASS_A_ITEMS,
    COUNT(CASE WHEN ABC_CLASS = 'B' THEN 1 END) AS CLASS_B_ITEMS,
    COUNT(CASE WHEN ABC_CLASS = 'C' THEN 1 END) AS CLASS_C_ITEMS,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM CLEANED_INVENTORY
WHERE CATEGORY IS NOT NULL
GROUP BY CATEGORY
ORDER BY CATEGORY_TOTAL_VALUE_USD DESC;

-- ============================================================================
-- END OF DYNAMIC TABLES
-- ============================================================================
