-- ============================================
-- DYNAMIC TABLES FOR REAL-TIME ANALYSIS
-- Purpose: Auto-refreshing tables for dashboard
-- ============================================

USE DATABASE inventory_app_db;
USE SCHEMA data_schema;
USE WAREHOUSE compute_wh;

-- ============================================
-- 1. DYNAMIC TABLE: CURRENT STOCK HEALTH
-- Auto-refreshes every 5 minutes
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE DT_STOCK_HEALTH
TARGET_LAG = '5 minutes'
WAREHOUSE = compute_wh
AS
SELECT 
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_LOCATION AS LOCATION,
    WAREHOUSE_ID,
    ABC_CLASS,
    
    -- Stock Levels
    QUANTITY_ON_HAND,
    QUANTITY_RESERVED,
    QUANTITY_COMMITTED,
    (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) AS AVAILABLE_STOCK,
    
    -- Thresholds
    REORDER_POINT,
    SAFETY_STOCK,
    LEAD_TIME_DAYS,
    
    -- Demand
    AVG_DAILY_SALES,
    FORECAST_NEXT_30D,
    
    -- Calculate Days Until Stockout
    CASE 
        WHEN AVG_DAILY_SALES > 0 THEN 
            ROUND((QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) / AVG_DAILY_SALES, 1)
        ELSE 999
    END AS DAYS_UNTIL_STOCKOUT,
    
    -- Stock Status
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 'OUT_OF_STOCK'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 'CRITICAL'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 'LOW'
        WHEN QUANTITY_ON_HAND <= (REORDER_POINT * 1.5) THEN 'MODERATE'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS,
    
    -- Risk Score (0-100)
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 100
        WHEN AVG_DAILY_SALES > 0 THEN 
            LEAST(100, ROUND(100 * (1 - ((QUANTITY_ON_HAND - QUANTITY_RESERVED) / (AVG_DAILY_SALES * LEAD_TIME_DAYS * 2))), 0))
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 90
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 70
        ELSE 20
    END AS RISK_SCORE,
    
    -- Financial
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE_USD,
    
    -- Supplier Info
    SUPPLIER_NAME,
    SUPPLIER_ID,
    SUPPLIER_ONTIME_PCT,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete');

-- ============================================
-- 2. DYNAMIC TABLE: ACTIVE ALERTS
-- Auto-refreshes every 10 minutes
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE DT_ACTIVE_ALERTS
TARGET_LAG = '10 minutes'
WAREHOUSE = compute_wh
AS
SELECT 
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_LOCATION AS LOCATION,
    ABC_CLASS,
    
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SAFETY_STOCK,
    AVG_DAILY_SALES,
    
    -- Alert Type
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 'STOCKOUT'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 'CRITICAL'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 'LOW_STOCK'
        WHEN AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 3 THEN 'URGENT'
        ELSE 'WARNING'
    END AS ALERT_TYPE,
    
    -- Priority
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 OR (AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 1) THEN 'CRITICAL'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK OR (AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 3) THEN 'HIGH'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT OR (AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 7) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS PRIORITY,
    
    -- Days Until Stockout
    CASE 
        WHEN AVG_DAILY_SALES > 0 THEN 
            ROUND((QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) / AVG_DAILY_SALES, 1)
        ELSE NULL
    END AS DAYS_UNTIL_STOCKOUT,
    
    LEAD_TIME_DAYS,
    SUPPLIER_NAME,
    SUPPLIER_ID,
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE_USD,
    
    -- Alert Age (days since last received)
    DATEDIFF('day', RECEIVED_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_RECEIVED,
    
    CURRENT_TIMESTAMP() AS ALERT_GENERATED_AT
FROM inventory_cleaned
WHERE (QUANTITY_ON_HAND <= REORDER_POINT 
       OR (AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 7))
  AND INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
ORDER BY 
    CASE PRIORITY
        WHEN 'CRITICAL' THEN 1
        WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3
        ELSE 4
    END,
    DAYS_UNTIL_STOCKOUT NULLS LAST;

-- ============================================
-- 3. DYNAMIC TABLE: REORDER RECOMMENDATIONS
-- Auto-refreshes every 30 minutes
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE DT_REORDER_RECOMMENDATIONS
TARGET_LAG = '30 minutes'
WAREHOUSE = compute_wh
AS
SELECT 
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_LOCATION AS LOCATION,
    WAREHOUSE_ID,
    ABC_CLASS,
    
    -- Current Status
    QUANTITY_ON_HAND,
    QUANTITY_RESERVED,
    QUANTITY_COMMITTED,
    (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) AS AVAILABLE_STOCK,
    
    -- Reorder Logic
    REORDER_POINT,
    SAFETY_STOCK,
    LEAD_TIME_DAYS,
    AVG_DAILY_SALES,
    FORECAST_NEXT_30D,
    
    -- Calculate Recommended Order Quantity
    -- Formula: (Safety Stock + (Avg Daily Sales * Lead Time)) - Available Stock
    CASE 
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN
            GREATEST(0, 
                ROUND(SAFETY_STOCK + (AVG_DAILY_SALES * LEAD_TIME_DAYS * 1.5) - 
                      (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED))
            )
        ELSE 0
    END AS RECOMMENDED_ORDER_QTY,
    
    -- Economic Order Quantity (EOQ) - Simplified
    CASE 
        WHEN AVG_DAILY_SALES > 0 THEN
            ROUND(SQRT(2 * AVG_DAILY_SALES * 30 * 10 / NULLIF(UNIT_COST_USD, 0)))
        ELSE REORDER_POINT
    END AS ECONOMIC_ORDER_QTY,
    
    -- Priority Score (1-10, higher = more urgent)
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 10
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK * 0.5 THEN 9
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 8
        WHEN QUANTITY_ON_HAND <= REORDER_POINT * 0.75 THEN 7
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 6
        ELSE 5
    END AS PRIORITY_SCORE,
    
    -- Financial Impact
    UNIT_COST_USD,
    CASE 
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN
            ROUND((SAFETY_STOCK + (AVG_DAILY_SALES * LEAD_TIME_DAYS * 1.5) - 
                   (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED)) * UNIT_COST_USD, 2)
        ELSE 0
    END AS ESTIMATED_ORDER_VALUE_USD,
    
    -- Supplier Details
    SUPPLIER_NAME,
    SUPPLIER_ID,
    SUPPLIER_ONTIME_PCT,
    
    -- Additional Context
    DAYS_OF_INVENTORY,
    ORDER_FREQUENCY_PER_MONTH,
    
    CURRENT_TIMESTAMP() AS RECOMMENDATION_GENERATED_AT
FROM inventory_cleaned
WHERE QUANTITY_ON_HAND <= REORDER_POINT
  AND INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
ORDER BY PRIORITY_SCORE DESC, ABC_CLASS, ESTIMATED_ORDER_VALUE_USD DESC;

-- ============================================
-- 4. DYNAMIC TABLE: LOCATION PERFORMANCE
-- Auto-refreshes every 1 hour
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE DT_LOCATION_PERFORMANCE
TARGET_LAG = '1 hour'
WAREHOUSE = compute_wh
AS
SELECT 
    WAREHOUSE_LOCATION AS LOCATION,
    WAREHOUSE_ID,
    
    -- Inventory Metrics
    COUNT(DISTINCT SKU_ID) AS TOTAL_SKUS,
    COUNT(DISTINCT CATEGORY) AS TOTAL_CATEGORIES,
    SUM(QUANTITY_ON_HAND) AS TOTAL_UNITS,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS TOTAL_VALUE_USD,
    
    -- Stock Health
    COUNT(CASE WHEN QUANTITY_ON_HAND <= 0 THEN 1 END) AS OUT_OF_STOCK_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > 0 AND QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) AS CRITICAL_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > SAFETY_STOCK AND QUANTITY_ON_HAND <= REORDER_POINT THEN 1 END) AS LOW_STOCK_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > REORDER_POINT THEN 1 END) AS HEALTHY_COUNT,
    
    -- Health Score (0-100)
    ROUND(100 * (1 - (
        (COUNT(CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) * 1.0) / 
        NULLIF(COUNT(DISTINCT SKU_ID), 0)
    )), 1) AS HEALTH_SCORE,
    
    -- Average Metrics
    ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DAYS_COVERAGE,
    ROUND(AVG(SUPPLIER_ONTIME_PCT), 1) AS AVG_SUPPLIER_PERFORMANCE,
    ROUND(AVG(DEMAND_FORECAST_ACCURACY_PCT), 1) AS AVG_FORECAST_ACCURACY,
    
    -- Top Issues
    SUM(CASE WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 1 ELSE 0 END) AS ITEMS_NEEDING_REORDER,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
GROUP BY WAREHOUSE_LOCATION, WAREHOUSE_ID;

-- ============================================
-- 5. DYNAMIC TABLE: CATEGORY HEATMAP DATA
-- Auto-refreshes every 15 minutes
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE DT_CATEGORY_HEATMAP
TARGET_LAG = '15 minutes'
WAREHOUSE = compute_wh
AS
SELECT 
    WAREHOUSE_LOCATION AS LOCATION,
    CATEGORY,
    
    -- SKU Counts by Status
    COUNT(DISTINCT SKU_ID) AS TOTAL_SKUS,
    COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND <= 0 THEN SKU_ID END) AS OUT_OF_STOCK_SKUS,
    COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND > 0 AND QUANTITY_ON_HAND <= SAFETY_STOCK THEN SKU_ID END) AS CRITICAL_SKUS,
    COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND > SAFETY_STOCK AND QUANTITY_ON_HAND <= REORDER_POINT THEN SKU_ID END) AS LOW_STOCK_SKUS,
    COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND > REORDER_POINT THEN SKU_ID END) AS HEALTHY_SKUS,
    
    -- Aggregate Metrics
    SUM(QUANTITY_ON_HAND) AS TOTAL_UNITS,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS TOTAL_VALUE_USD,
    ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DAYS_COVERAGE,
    
    -- Risk Assessment
    ROUND(AVG(CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 100
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 90
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 70
        ELSE 20
    END), 1) AS AVG_RISK_SCORE,
    
    -- Status for Heatmap Color
    CASE 
        WHEN COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND <= 0 THEN SKU_ID END) > 0 THEN 'OUT_OF_STOCK'
        WHEN COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN SKU_ID END) > 
             (COUNT(DISTINCT SKU_ID) * 0.3) THEN 'CRITICAL'
        WHEN COUNT(DISTINCT CASE WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN SKU_ID END) > 
             (COUNT(DISTINCT SKU_ID) * 0.5) THEN 'LOW'
        ELSE 'HEALTHY'
    END AS OVERALL_STATUS,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
GROUP BY WAREHOUSE_LOCATION, CATEGORY
ORDER BY AVG_RISK_SCORE DESC;

-- ============================================
-- VERIFY DYNAMIC TABLES
-- ============================================
SELECT 'Dynamic tables created successfully!' AS STATUS;

-- Check row counts
SELECT 'DT_STOCK_HEALTH' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DT_STOCK_HEALTH
UNION ALL
SELECT 'DT_ACTIVE_ALERTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DT_ACTIVE_ALERTS
UNION ALL
SELECT 'DT_REORDER_RECOMMENDATIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DT_REORDER_RECOMMENDATIONS
UNION ALL
SELECT 'DT_LOCATION_PERFORMANCE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DT_LOCATION_PERFORMANCE
UNION ALL
SELECT 'DT_CATEGORY_HEATMAP' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DT_CATEGORY_HEATMAP;
