-- ============================================
-- HEATMAP & STOCK HEALTH VIEWS
-- Purpose: Create optimized views for dashboard heatmaps
-- ============================================

USE DATABASE inventory_app_db;
USE SCHEMA data_schema;
USE WAREHOUSE compute_wh;

-- ============================================
-- 1. STOCK HEALTH BY LOCATION & ITEM
-- ============================================
CREATE OR REPLACE VIEW V_STOCK_HEALTH_MATRIX AS
SELECT 
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_LOCATION AS LOCATION,
    WAREHOUSE_ID,
    ABC_CLASS,
    
    -- Current Stock Levels
    QUANTITY_ON_HAND,
    QUANTITY_RESERVED,
    QUANTITY_COMMITTED,
    (QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) AS AVAILABLE_STOCK,
    
    -- Reorder Parameters
    REORDER_POINT,
    SAFETY_STOCK,
    LEAD_TIME_DAYS,
    
    -- Demand Metrics
    AVG_DAILY_SALES,
    FORECAST_NEXT_30D,
    DAYS_OF_INVENTORY,
    
    -- Calculate Days Until Stockout
    CASE 
        WHEN AVG_DAILY_SALES > 0 THEN 
            ROUND((QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) / AVG_DAILY_SALES, 1)
        ELSE NULL
    END AS DAYS_UNTIL_STOCKOUT,
    
    -- Stock Status Classification
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 'OUT_OF_STOCK'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 'CRITICAL'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 'LOW'
        WHEN QUANTITY_ON_HAND <= (REORDER_POINT * 1.5) THEN 'MODERATE'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS,
    
    -- Stock Level Percentage
    CASE 
        WHEN REORDER_POINT > 0 THEN 
            ROUND((QUANTITY_ON_HAND / REORDER_POINT) * 100, 1)
        ELSE 100
    END AS STOCK_LEVEL_PCT,
    
    -- Risk Score (0-100, higher = more urgent)
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 100
        WHEN AVG_DAILY_SALES > 0 THEN 
            LEAST(100, ROUND(100 * (1 - ((QUANTITY_ON_HAND - QUANTITY_RESERVED) / (AVG_DAILY_SALES * LEAD_TIME_DAYS * 2))), 0))
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 90
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 70
        ELSE 20
    END AS RISK_SCORE,
    
    -- Financial Impact
    UNIT_COST_USD,
    TOTAL_INVENTORY_VALUE_USD,
    
    -- Additional Context
    INVENTORY_STATUS,
    SUPPLIER_NAME,
    SUPPLIER_ID,
    EXPIRY_DATE,
    STOCK_AGE_DAYS,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
ORDER BY RISK_SCORE DESC, ABC_CLASS, CATEGORY;

-- ============================================
-- 2. LOCATION X CATEGORY AGGREGATION
-- ============================================
CREATE OR REPLACE VIEW V_LOCATION_CATEGORY_SUMMARY AS
SELECT 
    WAREHOUSE_LOCATION AS LOCATION,
    CATEGORY,
    COUNT(DISTINCT SKU_ID) AS TOTAL_SKUS,
    
    -- Stock Metrics
    SUM(QUANTITY_ON_HAND) AS TOTAL_STOCK,
    SUM(QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) AS AVAILABLE_STOCK,
    ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DAYS_INVENTORY,
    
    -- Status Counts
    COUNT(CASE WHEN QUANTITY_ON_HAND <= 0 THEN 1 END) AS OUT_OF_STOCK_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > 0 AND QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) AS CRITICAL_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > SAFETY_STOCK AND QUANTITY_ON_HAND <= REORDER_POINT THEN 1 END) AS LOW_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND > REORDER_POINT THEN 1 END) AS HEALTHY_COUNT,
    
    -- Risk Assessment
    ROUND(AVG(CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 100
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 90
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 70
        ELSE 20
    END), 1) AS AVG_RISK_SCORE,
    
    -- Financial
    SUM(TOTAL_INVENTORY_VALUE_USD) AS TOTAL_VALUE_USD,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
GROUP BY WAREHOUSE_LOCATION, CATEGORY
ORDER BY AVG_RISK_SCORE DESC, LOCATION, CATEGORY;

-- ============================================
-- 3. CRITICAL ITEMS REQUIRING IMMEDIATE ATTENTION
-- ============================================
CREATE OR REPLACE VIEW V_CRITICAL_ITEMS AS
SELECT 
    SKU_ID,
    SKU_NAME,
    CATEGORY,
    WAREHOUSE_LOCATION AS LOCATION,
    ABC_CLASS,
    
    QUANTITY_ON_HAND,
    REORDER_POINT,
    SAFETY_STOCK,
    AVG_DAILY_SALES,
    
    -- Days until stockout
    CASE 
        WHEN AVG_DAILY_SALES > 0 THEN 
            ROUND((QUANTITY_ON_HAND - QUANTITY_RESERVED - QUANTITY_COMMITTED) / AVG_DAILY_SALES, 1)
        ELSE 999
    END AS DAYS_UNTIL_STOCKOUT,
    
    -- Urgency level
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 'IMMEDIATE'
        WHEN AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 3 THEN 'URGENT'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 'HIGH'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 'MEDIUM'
        ELSE 'LOW'
    END AS URGENCY_LEVEL,
    
    -- Stock status
    CASE 
        WHEN QUANTITY_ON_HAND <= 0 THEN 'OUT_OF_STOCK'
        WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 'CRITICAL'
        WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 'LOW'
        ELSE 'MODERATE'
    END AS STOCK_STATUS,
    
    LEAD_TIME_DAYS,
    SUPPLIER_NAME,
    SUPPLIER_ID,
    SUPPLIER_ONTIME_PCT,
    UNIT_COST_USD,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE (QUANTITY_ON_HAND <= REORDER_POINT OR 
       (AVG_DAILY_SALES > 0 AND (QUANTITY_ON_HAND / AVG_DAILY_SALES) <= 7))
  AND INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
ORDER BY 
    CASE URGENCY_LEVEL
        WHEN 'IMMEDIATE' THEN 1
        WHEN 'URGENT' THEN 2
        WHEN 'HIGH' THEN 3
        WHEN 'MEDIUM' THEN 4
        ELSE 5
    END,
    ABC_CLASS,
    DAYS_UNTIL_STOCKOUT;

-- ============================================
-- 4. WAREHOUSE PERFORMANCE DASHBOARD
-- ============================================
CREATE OR REPLACE VIEW V_WAREHOUSE_PERFORMANCE AS
SELECT 
    WAREHOUSE_LOCATION AS LOCATION,
    WAREHOUSE_ID,
    
    COUNT(DISTINCT SKU_ID) AS TOTAL_SKUS,
    COUNT(DISTINCT CATEGORY) AS TOTAL_CATEGORIES,
    
    -- Stock Health
    SUM(QUANTITY_ON_HAND) AS TOTAL_UNITS,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS TOTAL_VALUE_USD,
    ROUND(AVG(DAYS_OF_INVENTORY), 1) AS AVG_DAYS_COVERAGE,
    
    -- Issue Counts
    COUNT(CASE WHEN QUANTITY_ON_HAND <= 0 THEN 1 END) AS OUT_OF_STOCK_ITEMS,
    COUNT(CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) AS CRITICAL_ITEMS,
    COUNT(CASE WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 1 END) AS LOW_STOCK_ITEMS,
    
    -- Health Score (0-100, higher = better)
    ROUND(100 * (1 - (
        COUNT(CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) * 1.0 / 
        NULLIF(COUNT(DISTINCT SKU_ID), 0)
    )), 1) AS HEALTH_SCORE,
    
    -- Quality Metrics
    ROUND(AVG(SUPPLIER_ONTIME_PCT), 1) AS AVG_SUPPLIER_ONTIME_PCT,
    ROUND(AVG(DEMAND_FORECAST_ACCURACY_PCT), 1) AS AVG_FORECAST_ACCURACY,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
GROUP BY WAREHOUSE_LOCATION, WAREHOUSE_ID
ORDER BY HEALTH_SCORE ASC, OUT_OF_STOCK_ITEMS DESC;

-- ============================================
-- 5. ABC ANALYSIS BY LOCATION
-- ============================================
CREATE OR REPLACE VIEW V_ABC_ANALYSIS AS
SELECT 
    WAREHOUSE_LOCATION AS LOCATION,
    ABC_CLASS,
    CATEGORY,
    
    COUNT(DISTINCT SKU_ID) AS SKU_COUNT,
    SUM(TOTAL_INVENTORY_VALUE_USD) AS TOTAL_VALUE_USD,
    SUM(QUANTITY_ON_HAND) AS TOTAL_UNITS,
    
    -- Stock Status
    COUNT(CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) AS CRITICAL_COUNT,
    COUNT(CASE WHEN QUANTITY_ON_HAND <= REORDER_POINT THEN 1 END) AS LOW_STOCK_COUNT,
    
    -- Percentages
    ROUND(100.0 * COUNT(CASE WHEN QUANTITY_ON_HAND <= SAFETY_STOCK THEN 1 END) / 
          NULLIF(COUNT(DISTINCT SKU_ID), 0), 1) AS CRITICAL_PCT,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM inventory_cleaned
WHERE INVENTORY_STATUS NOT IN ('Discontinued', 'Obsolete')
GROUP BY WAREHOUSE_LOCATION, ABC_CLASS, CATEGORY
ORDER BY ABC_CLASS, LOCATION, CATEGORY;

-- ============================================
-- VERIFY VIEWS
-- ============================================
SELECT 'Views created successfully!' AS STATUS;
SELECT COUNT(*) AS TOTAL_ITEMS FROM V_STOCK_HEALTH_MATRIX;
SELECT COUNT(*) AS CRITICAL_ITEMS FROM V_CRITICAL_ITEMS;
